#!/bin/bash

bold=$(tput bold)
red=$(tput setaf 1)
green=$(tput setaf 2)
underline=$(tput sgr 0 1)
blue=$(tput setaf 4)
purple=$(tput setaf 5)
reset=$(tput sgr0)
UPLINE=$(tput cuu1)
ERASELINE=$(tput el)

function help() {
cat<<EOF
        Not OK, man!
EOF
}

function invoke() {
#	echo "invoking: $1 || $2"

	local word="$1"
	local data="$2"

	shift 2

	curl -s "${URL}/${word}" --header "X-Auth-PSK: ${PASS}" --data-binary "${data}" "$@" >/dev/null
}

function invokeIrcCommand() {
	invoke IRCC \
		"<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\"><s:Body><u:X_SendIRCC xmlns:u=\"urn:schemas-sony-com:service:IRCC:1\"><IRCCCode>$1</IRCCCode></u:X_SendIRCC></s:Body></s:Envelope>" \
		--header "Connection: Keep-Alive" --header 'SOAPACTION: "urn:schemas-sony-com:service:IRCC:1#X_SendIRCC"' --header "Content-Type: text/xml; charset=UTF-8"
}

function getInputNames() {
        invoke "avContent" '{"method":"getContentList","id":88,"params":[{"stIdx":0,"cnt":50,"uri":"extInput:hdmi"}],"version":"1.5"}' | jq .result[][].title
}

function getInputs() {
        invoke "avContent" '{"method":"getContentList","id":88,"params":[{"stIdx":0,"cnt":50,"uri":"extInput:hdmi"}],"version":"1.5"}' 
}

function getInputUrls() {
        invoke "avContent" '{"method":"getContentList","id":88,"params":[{"stIdx":0,"cnt":50,"uri":"extInput:hdmi"}],"version":"1.5"}' | jq .result[][].uri
}

function getInputNameToUrlMapping() {
        invoke "avContent" '{"method":"getContentList","id":88,"params":[{"stIdx":0,"cnt":50,"uri":"extInput:hdmi"}],"version":"1.5"}' | jq ".result[][] | .title + \" —>\" + .uri "
}

function setInput() {
#	echo here1: $1
	invoke "avContent" "{\"method\":\"setPlayContent\",\"id\":101,\"params\":[{\"uri\":\"extInput:hdmi?port=${1}\"}],\"version\":\"1.0\"}"
}

#add following to .bashrc:
#
##sonyTv autocompletion
#[ -f /home/mmucha/Dropbox/skripty/bashScripts/tv ] && source <(/home/mmucha/Dropbox/skripty/bashScripts/tv autocomplete tv)
function autocomplete() {
	autocomplateFunction=_${1}_autocomplete
cat<<EOF
function ${autocomplateFunction}() {
	local cur="\${COMP_WORDS[COMP_CWORD]}"
	local prev="\${COMP_WORDS[COMP_CWORD-1]}"

	#something like index of word being autocompleted, counting from 1, and IIUC 1 is the name of command, ie, first param is 2
	local index="\${#COMP_WORDS[@]}"
	local first="\${COMP_WORDS[0]}"

	#echo \$index \$first \$cur \$prev \$COMP_CWORD done >> /tmp/debug
	if [[ \$index -eq 2 ]]; then
		COMPREPLY=( \$(compgen -W "multi-irq irq execute-irq keyboardRemote changeAudioSink changeDefaultAudioSink list-irq-data getInputUrls getInputNameToUrlMapping getInputNames getInputs setInput" -- \${cur}) )
	fi
}

complete -F ${autocomplateFunction} ${1}
EOF
}

function jqListAudioSinksTemplate() {
cat<<EOF
def parse:
  def interpret:
    if . == null then .
    elif startswith("\"") and endswith("\"")
    then  .[1:-1]
    else tonumber? // .
    end;
  (capture( "[ \t]*(?<key>[^:= ]*)(: | = )(?<value>.*)" ) // null)
  | if . then .value = (.value | interpret) else . end
;

# Construct one object for each "segment"  
def construct(s): 
  [ foreach (s, 0) as \$kv (null;
      if \$kv == 0 or \$kv.index
      then .complete = .accumulator | .accumulator = \$kv
      else .complete = null | .accumulator += \$kv
      end;
      .complete // empty ) ]
;


construct(inputs | parse | select(.) | {(.key):.value})
| map((.index|tostring)+" "+.["application.name"]+"(media=\""+.["media.name"]+"\", pid="+.["application.process.id"]+")")
| .[]

EOF
}


function changeAudioSink() {
	sinks=$(pacmd list-sink-inputs | jq -nRr -f <(jqListAudioSinksTemplate) | fzf -m --with-nth 2.. --bind ctrl-a:select-all,ctrl-d:deselect-all,ctrl-t:toggle-all | awk '{print $1}' )
	target=$(pacmd list-sinks | grep "index\|name:" | tr -d "\n" | sed "s/\* *index: \([0-9]*\)/index: \1(*)/;s/ *index: \([0-9]*\)/\1/g;s/[ \t]*name: <\([^>]*\)>/\t\1\n/g" | fzf | sed "s/^\([0-9]*\).*/\1/")
	echo "${sinks}" | xargs -I '{}' pacmd move-sink-input {} "${target}"
}

function changeDefaultAudioSink() {
	target=$(pacmd list-sinks | grep "index\|name:" | tr -d "\n" | sed "s/\* *index: \([0-9]*\)/index: \1(*)/;s/ *index: \([0-9]*\)/\1/g;s/[ \t]*name: <\([^>]*\)>/\t\1\n/g" | fzf | sed "s/^\([0-9]*\).*/\1/")
	pacmd set-default-sink "${target}"
}

#to regenerate: echo '{"method":"getRemoteControllerInfo","id":54,"params":[],"version":"1.0"}' | ./doc/launchOnSony.sh system | jq -c .result[1] | jq '. - map(. | select (.name | contains("Partner")) ) - map(. | select (.name | test("Num\\d")) )' | jq '.[] += {"type": "irq"}' | jq > /tmp/abc 
function irqCommandsJson() {
cat<<EOF
[
  {
    "name": "Enter",
    "value": "AAAAAQAAAAEAAAALAw==",
    "type": "irq"
  },
  {
    "name": "GGuide",
    "value": "AAAAAQAAAAEAAAAOAw==",
    "type": "irq"
  },
  {
    "name": "ChannelUp",
    "value": "AAAAAQAAAAEAAAAQAw==",
    "type": "irq"
  },
  {
    "name": "ChannelDown",
    "value": "AAAAAQAAAAEAAAARAw==",
    "type": "irq"
  },
  {
    "name": "VolumeUp",
    "value": "AAAAAQAAAAEAAAASAw==",
    "type": "irq"
  },
  {
    "name": "VolumeDown",
    "value": "AAAAAQAAAAEAAAATAw==",
    "type": "irq"
  },
  {
    "name": "Mute",
    "value": "AAAAAQAAAAEAAAAUAw==",
    "type": "irq"
  },
  {
    "name": "TvPower",
    "value": "AAAAAQAAAAEAAAAVAw==",
    "type": "irq"
  },
  {
    "name": "Audio",
    "value": "AAAAAQAAAAEAAAAXAw==",
    "type": "irq"
  },
  {
    "name": "MediaAudioTrack",
    "value": "AAAAAQAAAAEAAAAXAw==",
    "type": "irq"
  },
  {
    "name": "Tv",
    "value": "AAAAAQAAAAEAAAAkAw==",
    "type": "irq"
  },
  {
    "name": "Input",
    "value": "AAAAAQAAAAEAAAAlAw==",
    "type": "irq"
  },
  {
    "name": "TvInput",
    "value": "AAAAAQAAAAEAAAAlAw==",
    "type": "irq"
  },
  {
    "name": "TvAntennaCable",
    "value": "AAAAAQAAAAEAAAAqAw==",
    "type": "irq"
  },
  {
    "name": "WakeUp",
    "value": "AAAAAQAAAAEAAAAuAw==",
    "type": "irq"
  },
  {
    "name": "PowerOff",
    "value": "AAAAAQAAAAEAAAAvAw==",
    "type": "irq"
  },
  {
    "name": "Sleep",
    "value": "AAAAAQAAAAEAAAAvAw==",
    "type": "irq"
  },
  {
    "name": "Right",
    "value": "AAAAAQAAAAEAAAAzAw==",
    "type": "irq"
  },
  {
    "name": "Left",
    "value": "AAAAAQAAAAEAAAA0Aw==",
    "type": "irq"
  },
  {
    "name": "SleepTimer",
    "value": "AAAAAQAAAAEAAAA2Aw==",
    "type": "irq"
  },
  {
    "name": "Analog2",
    "value": "AAAAAQAAAAEAAAA4Aw==",
    "type": "irq"
  },
  {
    "name": "TvAnalog",
    "value": "AAAAAQAAAAEAAAA4Aw==",
    "type": "irq"
  },
  {
    "name": "Display",
    "value": "AAAAAQAAAAEAAAA6Aw==",
    "type": "irq"
  },
  {
    "name": "Jump",
    "value": "AAAAAQAAAAEAAAA7Aw==",
    "type": "irq"
  },
  {
    "name": "PicOff",
    "value": "AAAAAQAAAAEAAAA+Aw==",
    "type": "irq"
  },
  {
    "name": "PictureOff",
    "value": "AAAAAQAAAAEAAAA+Aw==",
    "type": "irq"
  },
  {
    "name": "Teletext",
    "value": "AAAAAQAAAAEAAAA/Aw==",
    "type": "irq"
  },
  {
    "name": "Video1",
    "value": "AAAAAQAAAAEAAABAAw==",
    "type": "irq"
  },
  {
    "name": "Video2",
    "value": "AAAAAQAAAAEAAABBAw==",
    "type": "irq"
  },
  {
    "name": "AnalogRgb1",
    "value": "AAAAAQAAAAEAAABDAw==",
    "type": "irq"
  },
  {
    "name": "Home",
    "value": "AAAAAQAAAAEAAABgAw==",
    "type": "irq"
  },
  {
    "name": "Exit",
    "value": "AAAAAQAAAAEAAABjAw==",
    "type": "irq"
  },
  {
    "name": "PictureMode",
    "value": "AAAAAQAAAAEAAABkAw==",
    "type": "irq"
  },
  {
    "name": "Confirm",
    "value": "AAAAAQAAAAEAAABlAw==",
    "type": "irq"
  },
  {
    "name": "Up",
    "value": "AAAAAQAAAAEAAAB0Aw==",
    "type": "irq"
  },
  {
    "name": "Down",
    "value": "AAAAAQAAAAEAAAB1Aw==",
    "type": "irq"
  },
  {
    "name": "ClosedCaption",
    "value": "AAAAAgAAAKQAAAAQAw==",
    "type": "irq"
  },
  {
    "name": "Component1",
    "value": "AAAAAgAAAKQAAAA2Aw==",
    "type": "irq"
  },
  {
    "name": "Component2",
    "value": "AAAAAgAAAKQAAAA3Aw==",
    "type": "irq"
  },
  {
    "name": "Wide",
    "value": "AAAAAgAAAKQAAAA9Aw==",
    "type": "irq"
  },
  {
    "name": "EPG",
    "value": "AAAAAgAAAKQAAABbAw==",
    "type": "irq"
  },
  {
    "name": "PAP",
    "value": "AAAAAgAAAKQAAAB3Aw==",
    "type": "irq"
  },
  {
    "name": "TenKey",
    "value": "AAAAAgAAAJcAAAAMAw==",
    "type": "irq"
  },
  {
    "name": "BSCS",
    "value": "AAAAAgAAAJcAAAAQAw==",
    "type": "irq"
  },
  {
    "name": "Ddata",
    "value": "AAAAAgAAAJcAAAAVAw==",
    "type": "irq"
  },
  {
    "name": "Stop",
    "value": "AAAAAgAAAJcAAAAYAw==",
    "type": "irq"
  },
  {
    "name": "Pause",
    "value": "AAAAAgAAAJcAAAAZAw==",
    "type": "irq"
  },
  {
    "name": "Play",
    "value": "AAAAAgAAAJcAAAAaAw==",
    "type": "irq"
  },
  {
    "name": "Rewind",
    "value": "AAAAAgAAAJcAAAAbAw==",
    "type": "irq"
  },
  {
    "name": "Forward",
    "value": "AAAAAgAAAJcAAAAcAw==",
    "type": "irq"
  },
  {
    "name": "DOT",
    "value": "AAAAAgAAAJcAAAAdAw==",
    "type": "irq"
  },
  {
    "name": "Rec",
    "value": "AAAAAgAAAJcAAAAgAw==",
    "type": "irq"
  },
  {
    "name": "Return",
    "value": "AAAAAgAAAJcAAAAjAw==",
    "type": "irq"
  },
  {
    "name": "Blue",
    "value": "AAAAAgAAAJcAAAAkAw==",
    "type": "irq"
  },
  {
    "name": "Red",
    "value": "AAAAAgAAAJcAAAAlAw==",
    "type": "irq"
  },
  {
    "name": "Green",
    "value": "AAAAAgAAAJcAAAAmAw==",
    "type": "irq"
  },
  {
    "name": "Yellow",
    "value": "AAAAAgAAAJcAAAAnAw==",
    "type": "irq"
  },
  {
    "name": "SubTitle",
    "value": "AAAAAgAAAJcAAAAoAw==",
    "type": "irq"
  },
  {
    "name": "CS",
    "value": "AAAAAgAAAJcAAAArAw==",
    "type": "irq"
  },
  {
    "name": "BS",
    "value": "AAAAAgAAAJcAAAAsAw==",
    "type": "irq"
  },
  {
    "name": "Digital",
    "value": "AAAAAgAAAJcAAAAyAw==",
    "type": "irq"
  },
  {
    "name": "Options",
    "value": "AAAAAgAAAJcAAAA2Aw==",
    "type": "irq"
  },
  {
    "name": "Media",
    "value": "AAAAAgAAAJcAAAA4Aw==",
    "type": "irq"
  },
  {
    "name": "Prev",
    "value": "AAAAAgAAAJcAAAA8Aw==",
    "type": "irq"
  },
  {
    "name": "Next",
    "value": "AAAAAgAAAJcAAAA9Aw==",
    "type": "irq"
  },
  {
    "name": "DpadCenter",
    "value": "AAAAAgAAAJcAAABKAw==",
    "type": "irq"
  },
  {
    "name": "CursorUp",
    "value": "AAAAAgAAAJcAAABPAw==",
    "type": "irq"
  },
  {
    "name": "CursorDown",
    "value": "AAAAAgAAAJcAAABQAw==",
    "type": "irq"
  },
  {
    "name": "CursorLeft",
    "value": "AAAAAgAAAJcAAABNAw==",
    "type": "irq"
  },
  {
    "name": "CursorRight",
    "value": "AAAAAgAAAJcAAABOAw==",
    "type": "irq"
  },
  {
    "name": "ShopRemoteControlForcedDynamic",
    "value": "AAAAAgAAAJcAAABqAw==",
    "type": "irq"
  },
  {
    "name": "FlashPlus",
    "value": "AAAAAgAAAJcAAAB4Aw==",
    "type": "irq"
  },
  {
    "name": "FlashMinus",
    "value": "AAAAAgAAAJcAAAB5Aw==",
    "type": "irq"
  },
  {
    "name": "DemoMode",
    "value": "AAAAAgAAAJcAAAB8Aw==",
    "type": "irq"
  },
  {
    "name": "Analog",
    "value": "AAAAAgAAAHcAAAANAw==",
    "type": "irq"
  },
  {
    "name": "Mode3D",
    "value": "AAAAAgAAAHcAAABNAw==",
    "type": "irq"
  },
  {
    "name": "DigitalToggle",
    "value": "AAAAAgAAAHcAAABSAw==",
    "type": "irq"
  },
  {
    "name": "DemoSurround",
    "value": "AAAAAgAAAHcAAAB7Aw==",
    "type": "irq"
  },
  {
    "name": "*AD",
    "value": "AAAAAgAAABoAAAA7Aw==",
    "type": "irq"
  },
  {
    "name": "AudioMixUp",
    "value": "AAAAAgAAABoAAAA8Aw==",
    "type": "irq"
  },
  {
    "name": "AudioMixDown",
    "value": "AAAAAgAAABoAAAA9Aw==",
    "type": "irq"
  },
  {
    "name": "PhotoFrame",
    "value": "AAAAAgAAABoAAABVAw==",
    "type": "irq"
  },
  {
    "name": "Tv_Radio",
    "value": "AAAAAgAAABoAAABXAw==",
    "type": "irq"
  },
  {
    "name": "SyncMenu",
    "value": "AAAAAgAAABoAAABYAw==",
    "type": "irq"
  },
  {
    "name": "Hdmi1",
    "value": "AAAAAgAAABoAAABaAw==",
    "type": "irq"
  },
  {
    "name": "Hdmi2",
    "value": "AAAAAgAAABoAAABbAw==",
    "type": "irq"
  },
  {
    "name": "Hdmi3",
    "value": "AAAAAgAAABoAAABcAw==",
    "type": "irq"
  },
  {
    "name": "Hdmi4",
    "value": "AAAAAgAAABoAAABdAw==",
    "type": "irq"
  },
  {
    "name": "TopMenu",
    "value": "AAAAAgAAABoAAABgAw==",
    "type": "irq"
  },
  {
    "name": "PopUpMenu",
    "value": "AAAAAgAAABoAAABhAw==",
    "type": "irq"
  },
  {
    "name": "OneTouchTimeRec",
    "value": "AAAAAgAAABoAAABkAw==",
    "type": "irq"
  },
  {
    "name": "OneTouchView",
    "value": "AAAAAgAAABoAAABlAw==",
    "type": "irq"
  },
  {
    "name": "DUX",
    "value": "AAAAAgAAABoAAABzAw==",
    "type": "irq"
  },
  {
    "name": "FootballMode",
    "value": "AAAAAgAAABoAAAB2Aw==",
    "type": "irq"
  },
  {
    "name": "iManual",
    "value": "AAAAAgAAABoAAAB7Aw==",
    "type": "irq"
  },
  {
    "name": "Netflix",
    "value": "AAAAAgAAABoAAAB8Aw==",
    "type": "irq"
  },
  {
    "name": "Assists",
    "value": "AAAAAgAAAMQAAAA7Aw==",
    "type": "irq"
  },
  {
    "name": "FeaturedApp",
    "value": "AAAAAgAAAMQAAABEAw==",
    "type": "irq"
  },
  {
    "name": "FeaturedAppVOD",
    "value": "AAAAAgAAAMQAAABFAw==",
    "type": "irq"
  },
  {
    "name": "GooglePlay",
    "value": "AAAAAgAAAMQAAABGAw==",
    "type": "irq"
  },
  {
    "name": "ActionMenu",
    "value": "AAAAAgAAAMQAAABLAw==",
    "type": "irq"
  },
  {
    "name": "Help",
    "value": "AAAAAgAAAMQAAABNAw==",
    "type": "irq"
  },
  {
    "name": "TvSatellite",
    "value": "AAAAAgAAAMQAAABOAw==",
    "type": "irq"
  },
  {
    "name": "WirelessSubwoofer",
    "value": "AAAAAgAAAMQAAAB+Aw==",
    "type": "irq"
  },
  {
    "name": "AndroidMenu",
    "value": "AAAAAgAAAMQAAABPAw==",
    "type": "irq"
  },
  {
    "name": "RecorderMenu",
    "value": "AAAAAgAAAMQAAABIAw==",
    "type": "irq"
  },
  {
    "name": "STBMenu",
    "value": "AAAAAgAAAMQAAABJAw==",
    "type": "irq"
  },
  {
    "name": "MuteOn",
    "value": "AAAAAgAAAMQAAAAsAw==",
    "type": "irq"
  },
  {
    "name": "MuteOff",
    "value": "AAAAAgAAAMQAAAAtAw==",
    "type": "irq"
  },
  {
    "name": "AudioOutput_AudioSystem",
    "value": "AAAAAgAAAMQAAAAiAw==",
    "type": "irq"
  },
  {
    "name": "AudioOutput_TVSpeaker",
    "value": "AAAAAgAAAMQAAAAjAw==",
    "type": "irq"
  },
  {
    "name": "AudioOutput_Toggle",
    "value": "AAAAAgAAAMQAAAAkAw==",
    "type": "irq"
  },
  {
    "name": "ApplicationLauncher",
    "value": "AAAAAgAAAMQAAAAqAw==",
    "type": "irq"
  },
  {
    "name": "YouTube",
    "value": "AAAAAgAAAMQAAABHAw==",
    "type": "irq"
  }
]
EOF
}

function getIrqCode() {
	irqCommandsJson | jq -r ".[] | select (.name==\"${1//\"/}\") | .value"
}

#———————————————————————————— remote ——————————————————————————————————————

function draw() {
cat<<EOF
Bash remote:

   ${bold}navigation${reset}: arrows           ${bold}HDMI-1${reset}: 1
   ${bold}confirm/enter${reset}: <ENTER>       ${bold}HDMI-2${reset}: 2
   ${bold}back${reset}: esc                    ${bold}HDMI-3${reset}: 3
   ${bold}mute${reset}: m                      ${bold}HDMI-4${reset}: 4
   ${bold}forward${reset}: "<PgUp>"            ${bold}Home${reset}: h
   ${bold}rewind${reset}: "<PgDown>"
   ${bold}exit${reset}: "<Esc>"                ${bold}Monitor${reset}: M
   ${bold}pause${reset}: "<SPACE>"             ${bold}TV${reset}: T
   ${bold}volumeUp${reset}: "+"                ${bold}Monitor-Tv mirroring${reset}: I
   ${bold}volumeDown${reset}: "-"              ${bold}Monitor-Tv composition${reset}: B
   ${bold}tvPower${reset}: "P"
   ${bold}screenOff${reset}: S                 ${bold}ChangeAppsAudioSink${reset}: A
   ${bold}youtube${reset}: y                   ${bold}ChangeDefaultAudioSink${reset}: D

   ${bold}quit${reset}: Q


Last selection(${SELECTION_INDEX}): ${1}
EOF
}

SCREEN_LINES=$(draw | wc -l)
MAX_LINE_LENGTH=$(( 20 + $(draw|wc -L) ))

function cr() {
	echo -en "\r";
}

function eraseLine() {
	echo -e "${UPLINE}\c"
}

function eraseAllScreenLines() {
	for J in $(seq 1 ${SCREEN_LINES}); do eraseLine;done
	cr
	#this is character repetition: head -c ${MAX_LINE_LENGTH} < /dev/zero | tr '\0' ' '
	for J in $(seq 1 ${SCREEN_LINES}); do  head -c ${MAX_LINE_LENGTH} < /dev/zero | tr '\0' ' ';echo;done
	for J in $(seq 1 ${SCREEN_LINES}); do eraseLine;done
}

function remoteCommand() {
    draw "${1}"
    invokeIrcCommand "${2}"

}

function keyboardRemote() {
	SELECTION_INDEX=0

	local forward="AAAAAgAAAJcAAAAcAw=="
	local rewind="AAAAAgAAAJcAAAAbAw=="
	local muteValue="AAAAAQAAAAEAAAAUAw=="
	local up="AAAAAQAAAAEAAAB0Aw=="
	local down="AAAAAQAAAAEAAAB1Aw=="
	local left="AAAAAQAAAAEAAAA0Aw=="
	local right="AAAAAQAAAAEAAAAzAw=="
	local exit="AAAAAQAAAAEAAABjAw=="
	local confirm="AAAAAQAAAAEAAABlAw=="
	local pause="AAAAAgAAAJcAAAAZAw=="
	local volumeUp="AAAAAQAAAAEAAAASAw=="
	local volumeDown="AAAAAQAAAAEAAAATAw=="
	local tvPower="AAAAAQAAAAEAAAAVAw=="
	local screenOff="AAAAAQAAAAEAAAA+Aw=="
	local youtube="AAAAAgAAAMQAAABHAw=="
	local hdmi1="AAAAAgAAABoAAABaAw=="
	local hdmi2="AAAAAgAAABoAAABbAw=="
	local hdmi3="AAAAAgAAABoAAABcAw=="
	local hdmi4="AAAAAgAAABoAAABdAw=="
	local home="AAAAAQAAAAEAAABgAw=="

	#first write screen with no button pressed.
	draw
	while true; do
		 unset K1 K2 K3
		 read -s -N1 
		 K1="$REPLY"
		 read -s -N2 -t 0.001
		 K2="$REPLY"
		 read -s -N1 -t 0.001
		 K3="$REPLY"
		 key="$K1$K2$K3"


		eraseAllScreenLines
		SELECTION_INDEX=$((${SELECTION_INDEX} + 1));

		case "$key" in
		#  $'\x1b\x5b\x32\x7e')  # Insert
		#   echo Insert Key
		#  ;;
		#  $'\x1b\x5b\x33\x7e')  # Delete
		#   echo Delete Key
		#  ;;
		#  $'\x1b\x5b\x31\x7e'|$'\x1b\x4f\x48'|$'\x1b\x5b\x48')  # Home_key_num_7
		#   echo Home Key
		#  ;;
		#  $'\x1b\x5b\x34\x7e'|$'\x1b\x4f\x46'|$'\x1b\x5b\x46')  # End_key_num_1
		#   echo End Key
		#  ;;
		  $'\x1b\x5b\x35\x7e')  # Page_Up
		   remoteCommand Page_Up ${forward}
		  ;;
		  $'\x1b\x5b\x36\x7e')  # Page_Down
		   remoteCommand Page_Down ${rewind}
		  ;;
		  $'\x1b\x5b\x41')  # Up_arrow
    			remoteCommand "Up arrow" ${up}
		  ;;
		  $'\x1b\x5b\x42')  # Down_arrow
		   remoteCommand "Down arrow" ${down}
		  ;;
		  $'\x1b\x5b\x43')  # Right_arrow
		   remoteCommand "Right arrow" ${right}
		  ;;
		  $'\x1b\x5b\x44')  # Left_arrow
		   remoteCommand "Left arrow" ${left}
		  ;;
		#  $'\x09')  # Tab
		#   echo Tab Key
		#  ;;
		  $'\x0a')  # Enter
		   remoteCommand "Enter Key" "${confirm}"
		  ;;
		  $'\x1b')  # Escape
		   remoteCommand "Escape Key" "${exit}"
		  ;;
		  $'\x20')  # Space
		   remoteCommand "Pause" "${pause}"
		  ;;
		  Q)
		#  echo
		   break;
		  ;;
                  +)
			remoteCommand "volumeUp" "${volumeUp}"
		  ;;
                  -)
			remoteCommand "volumeDown" "${volumeDown}"
		  ;;
                  m)
			remoteCommand "Mute" "${muteValue}"
		  ;;
                  P)
			remoteCommand "TvPower" "${tvPower}"
		  ;;
                  y)
			remoteCommand "Youtube" "${youtube}"
		  ;;
                  S)
			remoteCommand "ScreenOff" "${screenOff}"
		  ;;
                  1)
			remoteCommand "HDMI-1" "${hdmi1}"
		  ;;
                  2)
			remoteCommand "HDMI-2" "${hdmi2}"
		  ;;
                  3)
			remoteCommand "HDMI-3" "${hdmi3}"
		  ;;
                  4)
			remoteCommand "HDMI-4" "${hdmi4}"
		  ;;
                  h)
			remoteCommand "Home" "${home}"
		  ;;
                  A)
			changeAudioSink
			draw ""
		  ;;
                  M)
			  xrandr --output HDMI-0 --off --output DVI-D-0 --mode 1920x1200 --rate 59.95
			draw "Use Monitor only"
		  ;;
                  T)
			  xrandr --output HDMI-0 --mode 1920x1080 --rate 60.00 --output DVI-D-0 --off
			draw "Use TV only"
		  ;;
                  I)
			  guessedNoOfScreens=$(xrandr | grep " connected" | grep -E "[0-9]{3,4}x[0-9]{3,4}" | wc -l)
			  if [[ ${guessedNoOfScreens} -eq 1 ]]; then
				  xrandr --output HDMI-0 --auto --scale-from 1920x1200 --output DVI-D-0 --mode 1920x1200 --rate 59.95
				draw "Use Monitor-TV mirroring"
			  else
				  draw "Error: please switch to 1 screen only first"
			  fi
		  ;;
                  B)
			guessedNoOfScreens=$(xrandr | grep " connected" | grep -E "[0-9]{3,4}x[0-9]{3,4}" | wc -l)
                          if [[ ${guessedNoOfScreens} -eq 1 ]]; then
			  	xrandr --output DVI-D-0 --primary --mode 1920x1200 --rate 59.95 --output HDMI-0 --auto --scale-from 1920x1200 --right-of DVI-D-0
				draw "Use Monitor-TV composition"
                          else
                                  draw "Error: please switch to 1 screen only first"
                          fi
		  ;;
                  D)
			#changeAudioSink
		  ;;
		  *)
		   draw "<Unknown command>"
		  ;;
		 esac
	done
}
#//////////////////////////// remote //////////////////////////////////////
function runCommand() {
	if [[ $# -eq 0 ]]; then 
		keyboardRemote
		exit;
	fi

	local command="${1}"
	shift
	case "${command}" in
		help)
			help
			exit 0
			;;
		setInput)
			if [[ $# -eq 0 ]]; then
				echo -e "\tmissing input specification"
				help
				exit 1
			fi
			setInput "${1}"
			shift
			;;	
		getInputs)
			getInputs
			;;	
		keyboardRemote)
			keyboardRemote
			;;	
		getInputNames)
			getInputNames
			;;	
		getInputNameToUrlMapping)
			getInputNameToUrlMapping
			;;	
		getInputUrls)
			getInputUrls
			;;	
		changeAudioSink)
			changeAudioSink
			;;	
		changeDefaultAudioSink)
			changeDefaultAudioSink
			;;	

		execute-irq) 			
			cmd=$(irqCommandsJson | jq -r ".[] | select (.name==\"${1//\"/}\") | .value")
			invokeIrcCommand ${cmd}
			;;
		list-irq-data)
			irqCommandsJson
			;;
		irq)
				selection=$(irqCommandsJson | jq .[].name | nl -v 0| fzf --with-nth 2.. | awk '{print $1}')
				if [[ -n "${selection}" ]]; then 
					cmd=$(irqCommandsJson | jq -r ".[${selection}].value")
					invokeIrcCommand $cmd
					#echo $cmd
				else 
					echo "cancelled."	
				fi

			;;
		multi-irq)
				irqCommandsJson | jq .[].name | fzf --bind "enter:execute-silent( ${THIS_SCRIPT} execute-irq {} )"
			;;	
		autocomplete)
			autocomplete ${1-sonyTv}
			;;	

		*)
			echo -e "\tunknown command!"
			help
			exit 1
			;;
	esac
	
}



#———————————————————————————— MAIN ————————————————————————————————————————


SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
THIS_SCRIPT="${SCRIPTPATH}/$(basename ${0})"
URL=http://192.168.1.99/sony
PASS=pass


runCommand "$@" 

